# permissions for end users to edit gitopsdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitops-deploy-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitopsdeployment-editor-role
rules:
- apiGroups:
  - gitops.example.com
  resources:
  - gitopsdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.example.com
  resources:
  - gitopsdeployments/status
  verbs:
  - get
